#! /bin/zsh
open_apps() {
  echo 'Install apps:'
  echo 'Firefox:'
  open http://www.mozilla.org/en-US/firefox/new/
  sleep 1
  echo 'Dropbox:'
  open https://www.dropbox.com
  sleep 1
  echo 'Chrome:'
  open https://www.google.com/intl/en/chrome/browser/
  sleep 1
  echo 'Sequel Pro:'
  open http://www.sequelpro.com
  sleep 1
  echo 'Skype:'
  open http://www.skype.com/en/download-skype/skype-for-computer/
  sleep 1
  echo 'Toggl:'
  open https://www.toggl.com
  sleep 1
  echo 'Tower:'
  open http://www.git-tower.com
  sleep 1
  echo 'Transmission:'
  open http://www.transmissionbt.com
  sleep 1
  echo 'VLC:'
  open http://www.videolan.org/vlc/index.html
  sleep 1
  echo 'Pixelmator!'
}

echo 'Should I give you links for system applications (e.g. Skype, Tower, VLC)?'
echo 'n / y'
read give_links
[[ "$give_links" == 'y' ]] && open_apps
